[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
lib_deps = file://.
lib_compat_mode = off

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
