[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
lib_deps = file://.
lib_compat_mode = off
test_build_src = yes
build_flags = 
  -include test/test_string/native_compat.h

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
