[platformio]
default_envs = native

[env:native]
platform = native
test_framework = unity
lib_deps = file://.
lib_compat_mode = off
test_build_src = yes
build_flags = 
  -include test/test_string/native_compat.h

check_tool = cppcheck, clangtidy
check_flags =
  cppcheck: --enable=warning,style,performance,portability --inline-suppr
  clangtidy: --checks="bugprone-*,modernize-*,readability-*,-readability-magic-numbers,-readability-else-after-return,-modernize-use-trailing-return-type,-modernize-avoid-c-arrays,-cppcoreguidelines-*"

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
